---
connection:
  testfiles:
    Debug: '0'
    Folder_Sent: 't/sent'
    Server: files
    Folder_INBOX: 't/email-folder'
blocked:
  criteria:
    -
      body_like: netflix
      from_not_like: netflix.(com|no)$
    -
      subject_like: deilig[\s_]sex
  expiration_days: 0
  move_to: INBOX.Spam